# Generated by Django 3.0.8 on 2020-09-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200915_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_traider',
            new_name='user_status',
        ),
    ]
